// ==UserScript==
// @name         v0.3.7 AFT Tools Master CLEAN TEST
// @namespace    https://github.com/1Sirkkris
// @version      0.3.7
// @description  Clean AFT master: Each Multi Flip, Sku EditItems Loop, Datelot Expiration and MoveItems helper.
// @match        http://aft-qt-jp.aka.nrt.corp.amazon.com/app/edititems*
// @match        https://aft-qt-jp.aka.nrt.corp.amazon.com/app/edititems*
// @match        http://aft-qt-*.aka.*.corp.amazon.com/app/edititems*
// @match        https://aft-qt-*.aka.*.corp.amazon.com/app/edititems*
// @match        http://aft-qt-*.corp.amazon.com/app/edititems*
// @match        https://aft-qt-*.corp.amazon.com/app/edititems*
// @match        http://aft-qt-jp.aka.nrt.corp.amazon.com/app/moveitems*
// @match        https://aft-qt-jp.aka.nrt.corp.amazon.com/app/moveitems*
// @match        http://aft-qt-*.aka.*.corp.amazon.com/app/moveitems*
// @match        https://aft-qt-*.aka.*.corp.amazon.com/app/moveitems*
// @match        http://aft-qt-*.corp.amazon.com/app/moveitems*
// @match        https://aft-qt-*.corp.amazon.com/app/moveitems*
// @run-at       document-start
// @grant        none
// @updateURL    https://raw.githubusercontent.com/1Sirkkris/tampermonkey-scripts/main/scripts/AFT_Tools_Master_CLEAN_TEST.user.js
// @downloadURL  https://raw.githubusercontent.com/1Sirkkris/tampermonkey-scripts/main/scripts/AFT_Tools_Master_CLEAN_TEST.user.js
// ==/UserScript==

(() => {
  'use strict';
  if (window.__AFT_MASTER_V037__) return;
  window.__AFT_MASTER_V037__ = true;

  const VERSION='0.3.7',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const norm=v=>String(v??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim(),low=v=>norm(v).toLowerCase(),sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function visible(el){if(!el||!el.isConnected||el.disabled||el.getAttribute('aria-disabled')==='true')return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'}
  const pageText=()=>norm(document.body?.innerText||''),heading=()=>norm($$('h1,h2,h3,[role="heading"]').filter(visible).map(x=>x.textContent).find(Boolean)||'');
  function setValue(el,value,keepFocus=false){if(!el)return false;const proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,d=Object.getOwnPropertyDescriptor(proto,'value');el.focus();if(d?.set)d.set.call(el,String(value));else el.value=String(value);el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:String(value)}));el.dispatchEvent(new Event('change',{bubbles:true}));if(!keepFocus)el.blur();return true}
  function press(target,key){const code=key==='Enter'?'Enter':`Key${key.toUpperCase()}`,n=key==='Enter'?13:key.toUpperCase().charCodeAt(0);for(const type of ['keydown','keypress','keyup'])(target||document).dispatchEvent(new KeyboardEvent(type,{key,code,keyCode:n,which:n,bubbles:true,cancelable:true}))}
  const appInput=()=>$$('input[type="text"],input:not([type]),textarea').filter(visible).find(el=>!el.closest('.aftm'))||null;
  function button(words){const wanted=words.map(low);return $$('button,input[type="button"],input[type="submit"],a,[role="button"],span.a-button,div.a-button').filter(visible).filter(el=>!el.closest('.aftm')).find(el=>{const t=low(el.textContent||el.value||el.getAttribute('aria-label'));return t&&wanted.some(w=>t.includes(w))})||null}
  function click(words){const n=button(words);if(!n)return false;const real=n.querySelector?.('input.a-button-input,input[type="submit"],button')||n;if(!visible(real))return false;real.click();return true}
  async function waitFor(fn,timeout=12000,every=90,tokenFn=null,token=null){const start=Date.now();while(Date.now()-start<timeout){if(tokenFn&&tokenFn()!==token)return null;try{const v=fn();if(v)return v}catch{}await sleep(every)}return null}
  function radioByText(wanted){const w=low(wanted).replace(/_/g,' ');for(const r of $$('input[type="radio"]').filter(visible)){if(r.closest('.aftm'))continue;const id=r.id&&document.querySelector(`label[for="${CSS.escape(r.id)}"]`),label=id||r.closest('label')||r.parentElement,text=low(`${r.value||''} ${label?.textContent||''}`).replace(/_/g,' ');if(w==='sellable'){if(/\bsellable\b/.test(text)&&!/\bunsellable\b/.test(text))return r}else if(text.includes(w))return r}return null}
  function chooseRadio(label){const r=radioByText(label);if(!r)return false;r.click();r.dispatchEvent(new Event('input',{bubbles:true}));r.dispatchEvent(new Event('change',{bubbles:true}));return true}

  function injectCss(){if($('#aftm-style'))return;const s=document.createElement('style');s.id='aftm-style';s.textContent=`
    .aftm{position:fixed;z-index:2147483647;font:13px/1.35 Arial,sans-serif;box-shadow:0 8px 24px #0004}.aftm *{box-sizing:border-box}.aftm button{cursor:pointer;font-weight:700}.aftm input,.aftm textarea,.aftm select{width:100%;padding:7px;border:1px solid #91a0aa;border-radius:5px;background:#fff;color:#1d252b}.aftm select:disabled{opacity:.45;cursor:not-allowed;background:#e9ecef}
    #aftm-each{top:125px;left:15px;width:318px;background:#eef7fb;border:1px solid #527985;border-radius:8px;overflow:hidden;color:#172126}#aftm-each .timer{display:flex;align-items:center;justify-content:space-between;gap:8px;background:#e8f6ff;padding:7px 10px;font-weight:700;white-space:nowrap}#aftm-each .section-head{display:flex;align-items:center;justify-content:space-between;background:#174f59;color:#fff;padding:8px 10px;font-weight:800;cursor:pointer}#aftm-each .section-head button{width:25px;height:22px;padding:0;border:1px solid #9bb6bd;border-radius:5px;background:#123f47;color:#fff}#aftm-each .body{padding:10px;display:grid;gap:8px}#aftm-each[data-min="1"] .body{display:none}#aftm-each .primary{background:#225d67;color:#fff;border:0;padding:8px;border-radius:5px}#aftm-each .danger{background:#d94a4a;color:#fff;border:1px solid #b93737;padding:6px 10px;border-radius:6px}
    #aftm-sku,#aftm-datelot{right:12px;bottom:12px;width:304px;background:#f4f6f7;color:#1f2a30;border:1px solid #9aa8af;border-radius:10px;overflow:hidden}#aftm-sku .head,#aftm-datelot .head{display:flex;align-items:center;justify-content:space-between;background:#36545c;color:#fff;padding:9px 11px;font-weight:800}#aftm-sku .head button,#aftm-datelot .head button{width:28px;height:23px;padding:0;border:1px solid #9eb0b5;border-radius:5px;background:#294249;color:#fff}#aftm-sku .body,#aftm-datelot .body{padding:10px;display:grid;gap:8px}#aftm-sku[data-min="1"] .body,#aftm-datelot[data-min="1"] .body{display:none}#aftm-sku label,#aftm-datelot label{display:grid;gap:3px;font-weight:700}#aftm-sku .two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.aftm-row{display:flex;gap:7px}.aftm-row>*{flex:1}.aftm-run{background:#2f6f63!important;color:#fff!important;border:1px solid #25594f!important}.aftm-stop,.aftm-clear{background:#e8ecee;color:#182126;border:1px solid #a8b4ba}.aftm-status{font-weight:400;min-height:17px}`;document.documentElement.appendChild(s)}

  const Edit={active:false,mode:null,panel:null,running:false,token:0,keys:{q:'aftm_edit_q',active:'aftm_edit_active',done:'aftm_edit_done',total:'aftm_edit_total',sku:'aftm_sku_entry',currentState:'aftm_sku_current_state',currentDamage:'aftm_sku_current_damage',desiredState:'aftm_sku_desired_state',desiredDamage:'aftm_sku_desired_damage',skuMin:'aftm_sku_min',eachMin:'aftm_each_min',dateMin:'aftm_date_min'},match:()=>/\/app\/edititems/i.test(location.pathname),
    detect(){const t=pageText();if(/\bMode\s*:\s*Datelot\b/i.test(t))return'datelot';if(/\bMode\s*:\s*Each\b/i.test(t))return'each';if(/\bMode\s*:\s*Sku\b/i.test(t))return'sku';return null},
    start(){this.refresh()},stop(){this.token++;this.running=false;this.panel?.remove();this.panel=null;this.mode=null},
    refresh(){const m=this.detect();if(!m)return;if(m!==this.mode||!this.panel?.isConnected){this.mode=m;this.render()}if(localStorage.getItem(this.keys.active)==='1'&&!this.running)this.drive()},
    render(){this.panel?.remove();this.panel=this.mode==='each'?this.renderEach():this.mode==='sku'?this.renderSku():this.renderDatelot()},
    wireDamage(stateEl,damageEl){const sync=()=>{const enabled=low(stateEl.value)==='unsellable';damageEl.disabled=!enabled;if(!enabled)damageEl.blur()};stateEl.addEventListener('change',sync);sync()},
    wireMin(panel,key){const btn=$('[data-min]',panel);const set=on=>{panel.dataset.min=on?'1':'0';btn.textContent=on?'+':'−';localStorage.setItem(key,on?'1':'0')};set(localStorage.getItem(key)==='1');btn.onclick=e=>{e.stopPropagation();set(panel.dataset.min!=='1')};return set},

    renderEach(){const p=document.createElement('section');p.id='aftm-each';p.className='aftm';p.innerHTML=`<div class="timer"><span>⚡ Smart Auto Timer</span><button class="danger" data-clear>CLEAR</button></div><div class="section-head" data-toggle><span>Multi Flip</span><button data-min>−</button></div><div class="body"><label>Inventory State<select data-state><option>Sellable</option><option selected>Unsellable</option><option>Pending Research</option></select></label><label>Disposition<select data-disp><option>Amazon Damage</option><option>Defective</option><option>Distributor Damage</option><option>Expired</option></select></label><textarea data-list rows="6" placeholder="Paste:&#10;TOTE ASIN&#10;or&#10;TOTE ASIN FNSKU"></textarea><button class="primary" data-start>Start Multi Flip</button><div><b>Mode:</b> Each</div><div class="aftm-status" data-status>Idle</div></div>`;document.body.appendChild(p);const state=$('[data-state]',p),disp=$('[data-disp]',p);state.value=localStorage.getItem('aftm_each_state')||'Unsellable';disp.value=localStorage.getItem('aftm_each_disp')||'Amazon Damage';this.wireDamage(state,disp);const setMin=this.wireMin(p,this.keys.eachMin);$('[data-toggle]',p).onclick=e=>{if(e.target.closest('button'))return;setMin(p.dataset.min!=='1')};$('[data-start]',p).onclick=()=>this.startEach();$('[data-clear]',p).onclick=()=>this.clear('Cleared',true);return p},

    renderSku(){const p=document.createElement('section');p.id='aftm-sku';p.className='aftm';p.innerHTML=`<div class="head"><span>EditItems Loop v${VERSION}</span><button data-min>−</button></div><div class="body"><label>SKU / ASIN / FNSKU / FCSKU<input data-sku autocomplete="off"></label><div class="two"><label>Current state<select data-cur-state><option>Sellable</option><option>Unsellable</option><option>Pending Research</option></select></label><label>Current damage<select data-cur-dmg><option>Amazon Damage</option><option>Defective</option><option>Distributor Damage</option><option>Expired</option></select></label><label>Desired state<select data-new-state><option>Sellable</option><option>Unsellable</option><option>Pending Research</option></select></label><label>Desired damage<select data-new-dmg><option>Amazon Damage</option><option>Defective</option><option>Distributor Damage</option><option>Expired</option></select></label></div><div class="aftm-status" data-status>Idle</div><div class="aftm-row"><button class="aftm-run" data-run>RUN</button><button class="aftm-stop" data-stop>STOP</button><button class="aftm-clear" data-clear>CLEAR</button></div></div>`;document.body.appendChild(p);const sku=$('[data-sku]',p),cs=$('[data-cur-state]',p),cd=$('[data-cur-dmg]',p),ns=$('[data-new-state]',p),nd=$('[data-new-dmg]',p);sku.value=localStorage.getItem(this.keys.sku)||'';cs.value=localStorage.getItem(this.keys.currentState)||'Sellable';cd.value=localStorage.getItem(this.keys.currentDamage)||'Defective';ns.value=localStorage.getItem(this.keys.desiredState)||'Unsellable';nd.value=localStorage.getItem(this.keys.desiredDamage)||'Defective';this.wireDamage(cs,cd);this.wireDamage(ns,nd);const save=()=>{localStorage.setItem(this.keys.sku,norm(sku.value));localStorage.setItem(this.keys.currentState,cs.value);localStorage.setItem(this.keys.currentDamage,cd.value);localStorage.setItem(this.keys.desiredState,ns.value);localStorage.setItem(this.keys.desiredDamage,nd.value)};[sku,cs,cd,ns,nd].forEach(el=>el.addEventListener('change',save));sku.addEventListener('input',save);this.wireMin(p,this.keys.skuMin);$('[data-run]',p).onclick=()=>{document.activeElement?.blur?.();this.startSkuSingle()};$('[data-stop]',p).onclick=()=>{this.token++;this.running=false;localStorage.removeItem(this.keys.active);document.activeElement?.blur?.();this.status('Stopped')};$('[data-clear]',p).onclick=()=>this.clear('Cleared',true);return p},

    renderDatelot(){const p=document.createElement('section');p.id='aftm-datelot';p.className='aftm';p.innerHTML=`<div class="head"><span>Expiration Queue v${VERSION}</span><button data-min>−</button></div><div class="body"><label>Containers<textarea data-cont rows="5"></textarea></label><label>ASINs<textarea data-asins rows="4"></textarea></label><label>Expiration date<input data-date type="date"></label><label style="display:flex;grid-template-columns:auto 1fr;align-items:center;gap:7px"><input data-pr type="checkbox" style="width:auto"> Pending Research → Sellable</label><div class="aftm-status" data-status>Idle</div><div class="aftm-row"><button class="aftm-run" data-run>RUN</button><button class="aftm-stop" data-stop>STOP</button><button class="aftm-clear" data-clear>CLEAR</button></div></div>`;document.body.appendChild(p);this.wireMin(p,this.keys.dateMin);$('[data-run]',p).onclick=()=>{document.activeElement?.blur?.();this.startExpiration()};$('[data-stop]',p).onclick=()=>{this.token++;this.running=false;localStorage.removeItem(this.keys.active);document.activeElement?.blur?.();this.status('Stopped')};$('[data-clear]',p).onclick=()=>this.clear('Cleared',true);return p},

    status(t){const el=this.panel&&$('[data-status]',this.panel);if(el)el.textContent=t},queue(){try{const q=JSON.parse(localStorage.getItem(this.keys.q)||'[]');return Array.isArray(q)?q:[]}catch{return[]}},saveQueue(q){localStorage.setItem(this.keys.q,JSON.stringify(q))},clear(msg='Idle',clearFields=false){this.token++;this.running=false;[this.keys.q,this.keys.active,this.keys.done,this.keys.total,'aftm_edit_meta'].forEach(k=>localStorage.removeItem(k));if(clearFields&&this.panel){$$('input[type="text"],textarea,input[type="date"]',this.panel).forEach(el=>{el.value='';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))});$$('input[type="checkbox"]',this.panel).forEach(el=>el.checked=false);localStorage.removeItem(this.keys.sku)}document.activeElement?.blur?.();this.status(msg)},begin(items,meta){this.saveQueue(items);localStorage.setItem(this.keys.done,'0');localStorage.setItem(this.keys.total,String(items.length));localStorage.setItem(this.keys.active,'1');localStorage.setItem('aftm_edit_meta',JSON.stringify(meta));this.drive()},
    startEach(){const lines=$('[data-list]',this.panel).value.split(/\r?\n/).map(norm).filter(Boolean).map(line=>{const[location,asin,fnsku]=line.split(/\s+/);return{location,asin,fnsku:fnsku||asin}}).filter(x=>x.location&&x.asin);if(!lines.length){this.status('Paste TOTE ASIN rows');return}const state=$('[data-state]',this.panel).value,disp=$('[data-disp]',this.panel).value;localStorage.setItem('aftm_each_state',state);localStorage.setItem('aftm_each_disp',disp);this.begin(lines,{type:'each',state,disp})},
    startSkuSingle(){const sku=norm($('[data-sku]',this.panel).value);if(!sku){this.status('Enter SKU / ASIN / FNSKU / FCSKU');return}const meta={type:'sku',sku,currentState:$('[data-cur-state]',this.panel).value,currentDamage:$('[data-cur-dmg]',this.panel).value,desiredState:$('[data-new-state]',this.panel).value,desiredDamage:$('[data-new-dmg]',this.panel).value};this.begin([{sku}],meta)},
    startExpiration(){const containers=$('[data-cont]',this.panel).value.split(/\r?\n/).map(norm).filter(Boolean),asins=$('[data-asins]',this.panel).value.split(/\r?\n/).map(norm).filter(Boolean),date=$('[data-date]',this.panel).value,pr=$('[data-pr]',this.panel).checked;if(!containers.length||!asins.length||!date){this.status('Need containers, ASINs and date');return}const items=[];for(const location of containers)for(const asin of asins)items.push({location,asin});this.begin(items,{type:'expiration',date,pr})},
    step(){const h=low(heading()),t=low(pageText());if(t.includes('service failed')||t.includes('work is errored'))return'error';if(/^success\b/.test(h))return'success';if(h.includes('confirm change'))return'confirm';if(h.includes('select source inventory state'))return'sourceState';if(h.includes('select source disposition'))return'sourceDisp';if(h.includes('select new inventory state'))return'newState';if(h.includes('select new disposition'))return'newDisp';if(h.includes('expiration')||h.includes('date lot'))return'expiration';if(h.includes('input fnsku')||h.includes('input fcsku')||h.includes('input fnsku or fcsku')||h.includes('scan item'))return'item';if(h.includes('scan location')||h.includes('scan container'))return'location';return'unknown'},
    confirmMatches(meta){if(meta.type!=='sku')return true;const t=low(pageText()).replace(/_/g,' '),desired=low(meta.desiredState);if(desired==='sellable')return /targeted inventory state\s*:\s*(sellable|inventory)/.test(t)||/to\s*\[?sellable\]?/.test(t);if(desired==='pending research')return /targeted inventory state\s*:\s*pending research/.test(t)||/to\s*\[?pending research\]?/.test(t);if(desired==='unsellable')return /targeted inventory state\s*:\s*unsellable/.test(t)||t.includes(low(meta.desiredDamage));return true},
    async drive(){if(this.running)return;this.running=true;const tok=++this.token;try{while(this.active&&localStorage.getItem(this.keys.active)==='1'&&this.token===tok){const q=this.queue();if(!q.length){this.clear('Complete');break}const meta=JSON.parse(localStorage.getItem('aftm_edit_meta')||'{}'),current=q[0],step=this.step();this.status(step);if(step==='error'){click(['start over'])||press(document,'r')}else if(step==='location'){if(meta.type==='sku'){this.status('Waiting for SKU screen')}else{const i=await waitFor(()=>appInput(),10000,90,()=>this.token,tok);if(!i)break;setValue(i,current.location,true);await sleep(80);click(['continue'])||press(i,'Enter')}}else if(step==='item'){const value=meta.type==='sku'?meta.sku:(current.fnsku||current.asin),i=await waitFor(()=>appInput(),10000,90,()=>this.token,tok);if(!i)break;setValue(i,value,true);await sleep(100);click(['continue'])||press(i,'Enter')}else if(step==='sourceState'){const wanted=meta.type==='sku'?meta.currentState:(meta.pr?'Pending Research':'Sellable');if(!chooseRadio(wanted)){this.clear(`Stopped: source ${wanted} not found`);break}click(['continue'])}else if(step==='sourceDisp'){if(meta.type==='sku'&&low(meta.currentState)==='unsellable'&&!chooseRadio(meta.currentDamage)){this.clear(`Stopped: current damage not found`);break}click(['continue'])}else if(step==='newState'){const wanted=meta.type==='expiration'?'Sellable':(meta.type==='sku'?meta.desiredState:meta.state);if(!chooseRadio(wanted)){this.clear(`Stopped: target ${wanted} not found`);break}click(['continue'])}else if(step==='newDisp'){if(meta.type==='sku'&&low(meta.desiredState)==='unsellable'&&!chooseRadio(meta.desiredDamage)){this.clear(`Stopped: target damage not found`);break}else if(meta.type==='each'&&low(meta.state)==='unsellable')chooseRadio(meta.disp);click(['continue'])}else if(step==='expiration'){const dateInput=$$('input[type="date"],input').filter(visible).find(i=>!i.closest('.aftm')&&/date|expir/i.test([i.id,i.name,i.placeholder,i.getAttribute('aria-label')].map(norm).join(' ')))||appInput();if(dateInput){setValue(dateInput,meta.date,true);click(['save','continue','confirm'])||press(dateInput,'Enter')}}else if(step==='confirm'){if(!this.confirmMatches(meta)){this.clear(`STOPPED: confirm does not match ${meta.desiredState}`);break}click(['change items','confirm','continue'])||press(document,'Enter')}else if(step==='success'){q.shift();this.saveQueue(q);localStorage.setItem(this.keys.done,String(+(localStorage.getItem(this.keys.done)||0)+1));if(meta.type==='sku'){localStorage.removeItem(this.keys.active);this.status('Complete');break}click(['continue','start over'])||press(document,'Enter')}await sleep(250)}}finally{this.running=false}}
  };

  const MoveItems={active:false,busy:false,last:'',match:()=>/\/app\/moveitems/i.test(location.pathname),start(){this.refresh()},stop(){this.busy=false},async refresh(){if(!this.active||this.busy||!/enter quantity/i.test(pageText()))return;const qty=[...pageText().matchAll(/\bQuantity:\s*([0-9]{1,5})\b/gi)].map(m=>+m[1]).filter(n=>n>0).at(-1),i=$$('input').filter(visible).find(x=>/quantity|qty/i.test([x.id,x.name,x.placeholder].map(norm).join(' ')))||$$('input').filter(visible)[0];if(!qty||!i)return;const k=`${location.href}|${qty}`;if(k===this.last)return;this.last=k;this.busy=true;try{setValue(i,qty,true);await sleep(100);click(['continue'])||press(i,'Enter')}finally{this.busy=false}}};
  const modules=[Edit,MoveItems];let timer=0;function route(){clearTimeout(timer);timer=setTimeout(()=>{for(const m of modules){const yes=m.match();if(yes&&!m.active){m.active=true;m.start()}else if(!yes&&m.active){m.active=false;m.stop?.()}else if(yes)m.refresh?.()}},80)}function start(){injectCss();const mo=new MutationObserver(route);mo.observe(document.documentElement,{childList:true,subtree:true,characterData:true});window.addEventListener('hashchange',route,true);window.addEventListener('popstate',route,true);window.addEventListener('focus',route,true);route();console.log(`AFT Tools Master CLEAN TEST v${VERSION} loaded`)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();